# Generated by Django 4.0.4 on 2022-06-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_singleplayergame_delete_answer_question_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='singleplayergame',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
